const BATTLE_LIST_LEADER_BOARD_SEASON_STATUS = {
    PREVIEW: "PREVIEW",
    EXPIRED: "EXPIRED",
    INACTIVE: "INACTIVE",
    ACTIVE: "ACTIVE",
} as const;

export const BATTLE = {
    BATTLE_LIST_LEADER_BOARD_SEASON_STATUS,
}