enum PURPOSE_POLICY_AI {
    SPEAKING_EVALUATION = 'SPEAKING_EVALUATION', // Đánh giá phát âm SPEAKING
    PERSONALIZED_RECOMMENDATIONS = 'PERSONALIZED_RECOMMENDATIONS', // Gợi ý cá nhân hóa
    AI_KAIWA = 'AI_KAIWA',// Chat với AI
}

enum AI_POLICY_SCOPE {
    SELF_ONLY = 'SELF_ONLY',
    GROUP = 'GROUP',
    PUBLIC = 'PUBLIC',
}

enum SERVICE_TYPE {
    PERSONALIZED_RECOMMENDATIONS = 'PERSONALIZED_RECOMMENDATIONS', // Gợi ý cá nhân hóa
    AI_KAIWA = 'AI_KAIWA', // Hội thoại AI (AI Kaiwa)
}

export { PURPOSE_POLICY_AI, AI_POLICY_SCOPE, SERVICE_TYPE };